---
# tasks
- name: install essential packages
  apt: pkg={{ item}} update_cache=yes cache_valid_time=3600
  become: true
  become_method: sudo
  with_items:
    - build-essential
    - libncurses5-dev
    - libssl-dev
    - fop
    - xsltproc
    - unixodbc-dev
    - postgresql
    - postgresql-contrib
    - npm
    - libpq-dev
    - python-psycopg2

- name: check if node source is downloaded
  shell: ls /tmp/node-v{{ node_version }}-{{ node_platform }}.tar.xz
  register: node_downloaded
  ignore_errors: yes

- name: check if elixir source is downloaded
  shell: ls /tmp/otp_src_{{ erlang_version }}.tar.gz
  register: erlang_downloaded
  ignore_errors: yes

- name: check if elixir source is downloaded
  shell: ls /tmp/elixir-{{ elixir_version }}.tar.gz
  register: elixir_downloaded
  ignore_errors: yes

- name: download node src
  get_url:
    url: "{{ node_src }}"
    dest: "{{ download_path }}"
  when: node_downloaded|failed

- name: download erlang src
  get_url:
    url: "{{ erlang_src }}"
    dest: "{{ download_path }}"
  when: erlang_downloaded|failed

- name: download elixir src
  get_url:
    url: "{{ elixir_src }}"
    dest: "{{ download_path }}"
  when: elixir_downloaded|failed

- debug: msg="debug {{ elixir_downloaded }}"
  when: elixir_downloaded|failed

- debug: msg="debug {{ erlang_downloaded }}"
  when: erlang_downloaded|failed

- debug: msg="debug {{ node_downloaded }}"
  when: node_downloaded|failed
