---
# tasks
- name: install essential packages
  apt: pkg={{ item}} update_cache=yes cache_valid_time=3600
  become: true
  become_method: sudo
  with_items:
    - build-essential
    - libncurses5-dev
    - libssl-dev
    - fop
    - xsltproc
    - unixodbc-dev
    - postgresql
    - postgresql-contrib
    - npm
    - libpq-dev
    - python-psycopg2

- name: check if node source is downloaded
  shell: ls /tmp/node-v{{ node_version }}-{{ node_platform }}.tar.xz
  register: node_downloaded
  ignore_errors: yes

- name: check if erlang source is downloaded
  shell: ls /tmp/otp_src_{{ erlang_version }}.tar.gz
  register: erlang_downloaded
  ignore_errors: yes

- name: check if elixir source is downloaded
  shell: ls /tmp/elixir-{{ elixir_version }}.tar.gz
  register: elixir_downloaded
  ignore_errors: yes

- debug: msg="debug {{ elixir_downloaded }}"

- debug: msg="debug {{ erlang_downloaded }}"

- debug: msg="debug {{ node_downloaded }}"

- name: download node src
  get_url:
    url: "{{ node_src }}"
    dest: "{{ download_path }}"
  when: node_downloaded|failed

- name: download erlang src
  get_url:
    url: "{{ erlang_src }}"
    dest: "{{ download_path }}"
  when: erlang_downloaded|failed

- name: download elixir src
  get_url:
    url: "{{ elixir_src }}"
    dest: "{{ download_path }}"
  when: elixir_downloaded|failed

- name: unarchive node
  unarchive:
    src: /tmp/node-v{{ node_version }}-{{ node_platform }}.tar.xz
    dest: /tmp
  register: node_unarchived
  ignore_errors: true

- name: unarchive erlang
  unarchive:
    src: /tmp/otp_src_{{ erlang_version }}.tar.gz
    dest: /tmp
  register: erlang_unarchived
  ignore_errors: true

- name: unarchive elixir
  unarchive:
    src: /tmp/elixir-{{ elixir_version }}.tar.gz
    dest: /tmp
  register: elixir_unarchived
  ignore_errors: true

- name: add nodejs symlinks
  become: true
  become_method: sudo
  when: node_unarchived|success
  register: node_symlinked
  file:
    src: /tmp/node-v{{ node_version }}-{{ node_platform }}/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
    force: yes
    with_items:
      - node
      - npm

- name: update npm
  shell: npm install npm@latest -g
  when: node_symlinked|success
