---
# tasks
- name: install essential packages
  apt: pkg={{ item}} update_cache=yes cache_valid_time=3600
  become: true
  become_method: sudo
  with_items:
    - build-essential
    - libncurses5-dev
    - libssl-dev
    - fop
    - xsltproc
    - unixodbc-dev
    - postgresql
    - postgresql-contrib
    - npm
    - libpq-dev
    - python-psycopg2

- name: check if node source is downloaded
  shell: ls /tmp/node-v{{ node_version }}-{{ node_platform }}.tar.xz
  register: node_downloaded
  ignore_errors: yes

- name: check if elixir source is downloaded
  shell: ls /tmp/otp_src_{{ erlang_version }}.tar.gz
  register: erlang_downloaded
  ignore_errors: yes

- name: check if elixir source is downloaded
  shell: ls /tmp/elixir-{{ elixir_version }}.tar.gz
  register: elixir_downloaded
  ignore_errors: yes

- name: download node src
  get_url:
    url: "{{ node_src }}"
    dest: "{{ download_path }}"
  when: node_downloaded|failed

- name: download erlang src
  get_url:
    url: "{{ erlang_src }}"
    dest: "{{ download_path }}"
  when: erlang_downloaded|failed

- name: download elixir src
  get_url:
    url: "{{ elixir_src }}"
    dest: "{{ download_path }}"
  when: elixir_downloaded|failed

- name: unarchive nodejs
  command: tar -xvf node-v7.1.0-linux-x64.tar.xz
  args:
    chdir: /tmp
  register: node_unarchived
  when: node_downloaded|success

- name: unarchive erlang
  command: tar -xvf otp_src_19.1.tar.gz 
  args:
    chdir: /tmp
  register: erlang_unarchived
  when: erlang_downloaded|success

- name: unarchive elixir
  command: tar -xvf elixir-1.3.4.tar.gz
  args:
    chdir: /tmp
  register: elixir_unarchived
  when: elixir_downloaded|success

- name: add nodejs symlinks
  become: true
  become_method: sudo
  file:
    src: /tmp/node-v7.1.0-linux-x64/bin/{{ item }}
    dest: /usr/bin/{{ item }}
    state: link
    force: yes
  with_items:
    - node
    - npm
  register: node_symlinked

- debug: msg="debug {{ node_symlinked|success }}"

- name: update npm
  shell: npm install npm@latest -g
