---
download_path: /tmp
release_path: "{{ app_path }}/rel/{{ app_name }}/bin"
erlang_version: 19.1
erlang_src: http://www.erlang.org/download/otp_src_{{ erlang_version }}.tar.gz
elixir_version: 1.3.4
elixir_src: https://github.com/elixir-lang/elixir/archive/v{{ elixir_version }}.tar.gz
node_version: 7.1.0
node_platform: linux-x64
node_src: https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-{{ node_platform }}.tar.xz
node_downloaded: "{{ download_path }}/node-v{{ node_version }}-{{ node_platform }}.tar.xz
brunch_path: /node_modules/brunch/bin/
database_user: "{{ lookup('env', 'DB_USERNAME') }}"
database_pass: "{{ lookup('env', 'DB_PASSWORD') }}"
database_name: qconcursoclone_prod
app_name: qconcursoclone
app_repo: git@bitbucket.org:lucasweiblen/questions.git
app_path: /tmp/app
app_port: 5600
user: {local: lucasweiblen, remote: vagrant}
local_key_path: /Users/{{ user['local'] }}/.ssh
local_public_key: "{{ local_key_path }}/id_rsa.pub"
local_private_key: "{{ local_key_path }}/id_rsa"
remote_key_path: /home/{{ user['remote'] }}/.ssh
remote_public_key: "{{ remote_key_path }}/id_rsa.pub"
remote_private_key: "{{ remote_key_path }}/id_rsa"
locale: en_US.UTF-8
